### ISSUE TITLE
Не логинится

### ISSUE THREAD

**Issue by vkbot1** [ekonda/sketal#123]
Бот выдаёт ошибку 
> 
> python3.6 run.py
> [18.10.19 19:32:06] INFO    : Initializing bot
> [18.10.19 19:32:06] INFO    : Initializing vk clients
> Traceback (most recent call last):
>   File "/home/silent1snow/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 822, in _wrap_create_connection
>     return await self._loop.create_connection(*args, **kwargs)
>   File "/usr/lib/python3.6/asyncio/base_events.py", line 778, in create_connection
>     raise exceptions[0]
>   File "/usr/lib/python3.6/asyncio/base_events.py", line 765, in create_connection
>     yield from self.sock_connect(sock, address)
>   File "/usr/lib/python3.6/asyncio/selector_events.py", line 450, in sock_connect
>     return (yield from fut)
>   File "/usr/lib/python3.6/asyncio/selector_events.py", line 480, in _sock_connect_cb
>     raise OSError(err, 'Connect call failed %s' % (address,))
> ConnectionRefusedError: [Errno 111] Connect call failed ('87.240.129.75', 443)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "run.py", line 14, in <module>
>     bot = bot.Bot(BotSettings)
>   File "/home/silent1snow/sketal/bot.py", line 41, in __init__
>     self.api = VkController(settings, logger=self.logger, loop=self.loop)
>   File "/home/silent1snow/sketal/utils/plus.py", line 55, in __init__
>     loop.run_until_complete(self.init_vk())
>   File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
>     return future.result()
>   File "/home/silent1snow/sketal/utils/plus.py", line 73, in init_vk
>     await client.group(user[1])
>   File "/home/silent1snow/sketal/utils/api.py", line 210, in group
>     self_data = await self.method("groups.getById")
>   File "/home/silent1snow/sketal/utils/api.py", line 88, in method
>     async with self.session.post(url, data=data, **self.req_kwargs) as resp:
>   File "/home/silent1snow/.local/lib/python3.6/site-packages/aiohttp/client.py", line 855, in __aenter__
>     self._resp = await self._coro
>   File "/home/silent1snow/.local/lib/python3.6/site-packages/aiohttp/client.py", line 370, in _request
>     timeout=timeout
>   File "/home/silent1snow/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 445, in connect
>     proto = await self._create_connection(req, traces, timeout)
>   File "/home/silent1snow/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 757, in _create_connect
> ion
>     req, traces, timeout)
>   File "/home/silent1snow/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 879, in _create_direct_
> connection
>     raise last_exc
>   File "/home/silent1snow/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 862, in _create_direct_
> connection
>     req=req, client_error=client_error)
>   File "/home/silent1snow/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 829, in _wrap_create_co
> nnection
>     raise client_error(req.connection_key, exc) from exc
> aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.vk.com:443 ssl:None [Connect call fai
> led ('87.240.129.75', [443)]`]
Что это означает?

**Comment by michaelkrukov** [comment]
@vkbot1  "Cannot connect to host api.vk.com:443 ssl:None"

Либо вы в Украине, либо у вас не работает интернет, либо у вас проблемы с ssl на компьютере или сервере. Боюсь разбираться с этими вопросами вам лучше в интернете.
