### ISSUE TITLE
Не создает базу данных и выдает ошибку при поптыке логинится

### ISSUE THREAD

**Issue by DarsoX** [ekonda/sketal#127]
Код ошибки

18:29:39 - ERROR - Не удалось создать базу данных! Проверьте настройки и попробуйте снова!
18:29:39 - INFO - Приступаю к запуску VBot v5.0
18:29:39 - WARNING - Авторизация в ВКонтакте...
Traceback (most recent call last):
  File "/home/kotox/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 822, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 778, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.6/asyncio/base_events.py", line 765, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 450, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 480, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('87.240.129.76', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "vbot.py", line 325, in <module>
    bot = Bot()
  File "vbot.py", line 31, in __init__
    self.vk_init()
  File "vbot.py", line 101, in vk_init
    app_id=self.APP_ID)
  File "/home/kotox/vkplus.py", line 70, in __init__
    loop.run_until_complete(self.init_vk())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/home/kotox/vkplus.py", line 93, in init_vk
    await client.user(user[0], user[1], self.app_id, self.scope)
  File "/home/kotox/vkapi.py", line 184, in user
    self.token = await get_token(username, password, app_id, scope)
  File "/home/kotox/vkapi.py", line 276, in get_token
    await login(username, password, session)
  File "/home/kotox/vkapi.py", line 341, in login
    async with session.get(url_login) as resp:
  File "/home/kotox/.local/lib/python3.6/site-packages/aiohttp/client.py", line 855, in __aenter__
    self._resp = await self._coro
  File "/home/kotox/.local/lib/python3.6/site-packages/aiohttp/client.py", line 370, in _request
    timeout=timeout
  File "/home/kotox/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 445, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/kotox/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 757, in _create_connection
    req, traces, timeout)
  File "/home/kotox/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 879, in _create_direct_connection
    raise last_exc
  File "/home/kotox/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 862, in _create_direct_connection
    req=req, client_error=client_error)
  File "/home/kotox/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 829, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host m.vk.com:443 ssl:None [Connect call failed ('87.240.129.76', 443)]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f8dbb085ba8>

**Comment by michaelkrukov** [comment]
```
Cannot connect to host m.vk.com:443 
```

Не удалось соедениться с вконтакте. Проверьте интернет, убедитесь, что сервер или компьютер, на котором запускается бот имеет возможность зайти (в Украине ВК заблокирован, если что).
